# Generated by Django 4.0.5 on 2022-09-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=255)),
                ('listing_price', models.FloatField()),
            ],
            options={
                'db_table': 'property',
            },
        ),
    ]
